version: "2.4"

services:
  docker-wireguard:
    # env_file:
    #   - ./.env
    build: ./build
    image: docker-wireguard:0.1
    volumes:
      - ./conf.d:/etc/wireguard/conf.d
    ports:
      - "51820:51820/udp" #doesn't work without /udp https://github.com/moby/moby/issues/15127
    cap_add:
      - NET_ADMIN
